### ISSUE TITLE
What plateform (Windows, iOS, Linux) ?

### ISSUE THREAD

**Issue by Cyrille37** [nunomaduro/laravel-desktop-notifier#15]
Hello,
The readme missing some words about compatibles plateforms.
Cheers.

**Comment by nunomaduro** [comment]
Hey @Cyrille37 👋

Can you do a PR for that?

**Comment by Cyrille37** [comment]
But I've not the answer ...

**Comment by tahseen2k8** [comment]
nunomaduro . have you tested it on Linux .? 
this looks not working on Ubuntu

**Comment by nunomaduro** [comment]
After checking the JoliNotif repository, this package should work on Windows, Mac and Linux. I will update the readme. Thanks @Cyrille37.
