### ISSUE TITLE
is this generic for all browser of user specific

### ISSUE THREAD

**Issue by tahseen2k8** [nunomaduro/laravel-desktop-notifier#16]
was looking you package it is super easy for desktop notification .

I have a question hope you never mind to answer such a foolish question :D

when ever it trigger notify method does it show on all systems where ever our app is open or jus specific users . 

let say i am calling it on a condition  where login_userId =2 . what happen i have 10 active users that time.
does it show only for user id 2 or all .

TIA for your quick response.

**Comment by nunomaduro** [comment]
@tahseen2k8 This package **can NOT send remote** desktop notifications. This only triggers desktop notifications where your Laravel application is running.

Please tell me if something is not clear for you.

**Comment by tahseen2k8** [comment]
@nunomaduro  thanks but the notification is not working on Ubuntu i am trying on  18.04+ showing no error but the proc_open looks not working any specific permission need to grant .?

**Comment by nunomaduro** [comment]
@tahseen2k8 This package is just a wrapper. Please create an issue on this repository: https://github.com/jolicode/JoliNotif.
