### ISSUE TITLE
Notification Title & Icon Issues

### ISSUE THREAD

**Issue by RichieMcMullen** [nunomaduro/laravel-desktop-notifier#26]
Works fine on iMac. The notification window title (not the message title) says ```Script Editor```. Would be nice to be able to set that to something else.

Also, I cannot get the icon to display. Im using the resource_path, I've tried public_path, absolute url etc... nothing seems to set the icon.

**Comment by owenvoke** [comment]
On Mac, you need to use [Terminal Notifier](https://github.com/julienXX/terminal-notifier) in order for the title and icon to be displayed. I thought I'd added a note, but that was in [Laravel Zero](https://github.com/laravel-zero/laravel-zero/issues/197#issuecomment-717961655).

Feel free to add a note regarding this to the README, if not I'll add one when I get time. 👍🏻

**Comment by RichieMcMullen** [comment]
Ok thanks for your quick response!
