### ISSUE TITLE
Receive desktop notification when browser is closed

### ISSUE THREAD

**Issue by Echecivuole** [nunomaduro/laravel-desktop-notifier#30]
Hi, how does the desktop notification work when browser is closed? If I apply a notification to appear to another user when I create a task for him and he has the browser closed, he doesn't receive desktop notification.

**Comment by nunomaduro** [comment]
I don't know. You need to test it.

**Comment by Echecivuole** [comment]
Hello, I tested and it didn't work. If the package is desktop notifier it should also provide guidance to send notification when the browser is closed....

**Comment by owenvoke** [comment]
This is designed for console commands, it won't appear in a user's browser. 🤔 It only appears on the machine that is running the command.

**Comment by Echecivuole** [comment]
yes not appearing in the browser, but if I have Laravel website which triggers the console command to another user is this package able to send the console command in the other user's desktop? Otherwise which is the advantage of having a desktop notifier if I cannot t receive notifications even when I am not on the laravel site triggering the notification?

**Comment by nunomaduro** [comment]
That's not possible with this package.

**Comment by Echecivuole** [comment]
thanks for prompt support. So this package can be used only if I want to receive notifications from commands run from the same pc

**Comment by nunomaduro** [comment]
Correct.
