### ISSUE TITLE
Unable to read app property, I think the Command has change $app property to $laravel

### ISSUE THREAD

**Issue by jvrsolis** [nunomaduro/laravel-desktop-notifier#8]
php artisan desktop:example

   ErrorException  : Undefined property: App\Console\Commands\DesktopNotification::$app

  at /home/vagrant/code/wc2/vendor/nunomaduro/laravel-desktop-notifier/src/LaravelDesktopNotifierServiceProvider.php: 42
    38|          */
    39|         Command::macro(
    40|             'notify',
    41|             function (string $text, string $body, $icon = null) {
  > 42|                 $notifier = $this->app[Contracts\Notifier::class];
    43|
    44|                 $notification = $this->app[Contracts\Notification::class]
    45|                     ->setTitle($text)
    46|                     ->setBody($body);

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined property: App\Console\Commands\DesktopNotification::$app", "/home/vagrant/code/wc2/vendor/nunomaduro/laravel-desktop-notifier/src/LaravelDesktopNotifierServiceProvider.php", ["Hello Web Artisan", "Love beautiful code? We do too!"])
      /home/vagrant/code/wc2/vendor/nunomaduro/laravel-desktop-notifier/src/LaravelDesktopNotifierServiceProvider.php : 42

  2   App\Console\Commands\DesktopNotification::NunoMaduro\LaravelDesktopNotifier\{closure}("Hello Web Artisan", "Love beautiful code? We do too!")
      /home/vagrant/code/wc2/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php : 106

**Comment by nunomaduro** [comment]
@Javier-Solis Problem should be fixed now on the version `v2.0.3`.

Please perform a `composer update nunomaduro/laravel-desktop-notifier` and tell me the results 👍

**Comment by nunomaduro** [comment]
This should be fixed.
